# ================================================================
# Simplified Local Setup - No Coolify API Required
# ================================================================
# This script sets up your local environment without needing
# Coolify API access. You'll manually export the database once.
# ================================================================

param(
    [string]$DatabaseDumpFile = "",  # Path to existing database dump (optional)
    [switch]$SkipDatabase            # Skip database import if you don't have a dump yet
)

$ErrorActionPreference = "Stop"

Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║                                                                ║" -ForegroundColor Cyan
Write-Host "║     Trading Nexus - Simplified Local Setup (No Coolify)       ║" -ForegroundColor Cyan
Write-Host "║                                                                ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ===== STEP 1: Rebuild Docker Images =====
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host "  STEP 1/4: Rebuilding Docker Images" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host ""

Write-Host "[1/3] Stopping existing containers..." -ForegroundColor Yellow
docker compose down 2>$null
Write-Host "✅ Containers stopped" -ForegroundColor Green
Write-Host ""

Write-Host "[2/3] Building backend image..." -ForegroundColor Yellow
docker compose build --no-cache backend
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Backend build failed" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Backend built" -ForegroundColor Green
Write-Host ""

Write-Host "[3/3] Building frontend image..." -ForegroundColor Yellow
docker compose build --no-cache frontend
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Frontend build failed" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Frontend built" -ForegroundColor Green
Write-Host ""

# ===== STEP 2: Create Local Configuration =====
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host "  STEP 2/4: Creating Local Configuration" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host ""

$envContent = @"
# ================================================================
# Trading Nexus - Local Development Environment
# Auto-generated by local_setup_simplified.ps1
# ================================================================

# --- Database (Local PostgreSQL) ---
DB_PASSWORD=postgres123

# --- Mock Dhan Engine Credentials (Local) ---
DHAN_CLIENT_ID=mock_client
DHAN_API_KEY=mock_api_key
DHAN_API_SECRET=mock_api_secret
DHAN_PIN=
DHAN_TOTP_SECRET=
DHAN_ACCESS_TOKEN=mock_access_token

# --- Mock Dhan Endpoints ---
DHAN_BASE_URL=http://mockdhan:9000/v2
DHAN_FEED_URL=ws://mockdhan:9000
DHAN_DEPTH_20_URL=ws://mockdhan:9000/twentydepth

# --- Local Configuration ---
VPS_IP=localhost
DOMAIN=localhost

# --- Feature Flags (Local Development) ---
# Streams enabled against local mockdhan service (no production connectivity)
DISABLE_DHAN_WS=false
DISABLE_MARKET_STREAMS=false
STARTUP_START_STREAMS=true
STARTUP_LOAD_MASTER=true
STARTUP_LOAD_TIER_B=true

# --- Optional Settings ---
GREEKS_POLL_SECONDS=15
LOG_LEVEL=DEBUG

"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8 -Force
Write-Host "✅ Local .env file created" -ForegroundColor Green
Write-Host "   • Dhan credentials: MOCK values" -ForegroundColor Gray
Write-Host "   • Market streams: ENABLED (mockdhan)" -ForegroundColor Gray
Write-Host "   • Mock engine URLs: configured" -ForegroundColor Gray
Write-Host "   • Database: Local PostgreSQL" -ForegroundColor Gray
Write-Host ""

# ===== STEP 3: Handle Database =====
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host "  STEP 3/4: Database Setup" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host ""

if ($SkipDatabase) {
    Write-Host "⏭️  Skipping database import (you can do this manually later)" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To import database later:" -ForegroundColor Cyan
    Write-Host "  1. Get database dump from production" -ForegroundColor Gray
    Write-Host "  2. Run: docker cp dump.sql trading_nexus_db:/tmp/" -ForegroundColor Gray
    Write-Host "  3. Run: docker exec trading_nexus_db psql -U postgres -d trading_nexus -f /tmp/dump.sql" -ForegroundColor Gray
    Write-Host ""
} elseif ($DatabaseDumpFile -and (Test-Path $DatabaseDumpFile)) {
    Write-Host "[1/4] Starting PostgreSQL..." -ForegroundColor Yellow
    docker compose up -d db
    Start-Sleep -Seconds 15
    Write-Host "✅ PostgreSQL started" -ForegroundColor Green
    Write-Host ""
    
    Write-Host "[2/4] Preparing database..." -ForegroundColor Yellow
    docker exec trading_nexus_db psql -U postgres -c "DROP DATABASE IF EXISTS trading_nexus;" 2>$null
    docker exec trading_nexus_db psql -U postgres -c "CREATE DATABASE trading_nexus;" 2>$null
    Write-Host "✅ Database prepared" -ForegroundColor Green
    Write-Host ""
    
    Write-Host "[3/4] Copying dump file..." -ForegroundColor Yellow
    docker cp $DatabaseDumpFile trading_nexus_db:/tmp/import.sql
    Write-Host "✅ Dump copied" -ForegroundColor Green
    Write-Host ""
    
    Write-Host "[4/4] Importing data..." -ForegroundColor Yellow
    docker exec trading_nexus_db psql -U postgres -d trading_nexus -f /tmp/import.sql
    Write-Host "✅ Database imported" -ForegroundColor Green
    Write-Host ""
} else {
    Write-Host "ℹ️  No database dump provided" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "The local environment will start with an empty database." -ForegroundColor Yellow
    Write-Host "Migration scripts will create the schema automatically." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To get production data, you can:" -ForegroundColor Cyan
    Write-Host "  Option 1: Connect to your VPS via SSH and run:" -ForegroundColor Gray
    Write-Host "    docker exec <db_container> pg_dump -U postgres trading_terminal > dump.sql" -ForegroundColor Gray
    Write-Host "    Then copy dump.sql here and re-run this script with:" -ForegroundColor Gray
    Write-Host "    .\local_setup_simplified.ps1 -DatabaseDumpFile dump.sql" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  Option 2: Test with empty database (good for development)" -ForegroundColor Gray
    Write-Host ""
    
    $proceed = Read-Host "Continue with empty database? (Y/n)"
    if ($proceed -eq "n" -or $proceed -eq "N") {
        Write-Host "Setup cancelled. Get a database dump and re-run." -ForegroundColor Yellow
        exit 0
    }
}

# ===== STEP 4: Start Services =====
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host "  STEP 4/4: Starting All Services" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
Write-Host ""

Write-Host "Starting all Docker services..." -ForegroundColor Yellow
docker compose up -d

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Failed to start services" -ForegroundColor Red
    exit 1
}
Write-Host "✅ All services started" -ForegroundColor Green
Write-Host ""

Write-Host "Waiting for services to be healthy (30 seconds)..." -ForegroundColor Yellow
Start-Sleep -Seconds 30
Write-Host ""

# Show status
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  Container Status:" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
docker compose ps
Write-Host ""

# Test connectivity
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  Testing Services:" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green

try {
    $response = Invoke-WebRequest -Uri "http://localhost:8000/health" -UseBasicParsing -TimeoutSec 5 -ErrorAction SilentlyContinue
    if ($response.StatusCode -eq 200) {
        Write-Host "✅ Backend API: Responding" -ForegroundColor Green
    }
} catch {
    Write-Host "⚠️  Backend API: Not ready yet (may need more time)" -ForegroundColor Yellow
}

try {
    $response = Invoke-WebRequest -Uri "http://localhost" -UseBasicParsing -TimeoutSec 5 -ErrorAction SilentlyContinue
    if ($response.StatusCode -eq 200) {
        Write-Host "✅ Frontend: Responding" -ForegroundColor Green
    }
} catch {
    Write-Host "⚠️  Frontend: Not ready yet (may need more time)" -ForegroundColor Yellow
}

Write-Host ""

# ===== COMPLETION =====
Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                                                                ║" -ForegroundColor Green
Write-Host "║              🎉 LOCAL SETUP COMPLETE! 🎉                       ║" -ForegroundColor Green
Write-Host "║                                                                ║" -ForegroundColor Green
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

Write-Host "📌 Access Your Local Environment:" -ForegroundColor Cyan
Write-Host "   • Frontend:      http://localhost" -ForegroundColor White
Write-Host "   • Backend API:   http://localhost:8000" -ForegroundColor White
Write-Host "   • API Docs:      http://localhost:8000/docs" -ForegroundColor White
Write-Host "   • Database:      localhost:5432" -ForegroundColor White
Write-Host ""

Write-Host "✨ Key Features:" -ForegroundColor Cyan
Write-Host "   • No DhanHQ credentials needed" - ForegroundColor Gray
Write-Host "   • Market streams disabled (safe)" -ForegroundColor Gray
Write-Host "   • Database: $( if ($DatabaseDumpFile) { 'Production data imported' } elseif ($SkipDatabase) { 'Empty (import manually)' } else { 'Empty (migrations will create schema)' })" -ForegroundColor Gray
Write-Host "   • Debug logging enabled" -ForegroundColor Gray
Write-Host ""

Write-Host "🔧 Useful Commands:" -ForegroundColor Yellow
Write-Host "  docker compose logs -f backend    # View backend logs" -ForegroundColor Gray
Write-Host "  docker compose restart backend    # Restart after code changes" -ForegroundColor Gray
Write-Host "  docker compose down               # Stop all services" -ForegroundColor Gray
Write-Host ""

Write-Host "Happy coding! 🚀" -ForegroundColor Cyan
Write-Host ""
