# ================================================================
# Script 4: Synchronize Configuration & Settings
# ================================================================
# This script fetches and synchronizes all configuration files
# and settings from production to local environment
# ================================================================

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  Trading Nexus - Local Environment Setup - Step 4" -ForegroundColor Cyan
Write-Host "  Synchronizing Configuration Files" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

Write-Host "📋 Configuration items to sync:" -ForegroundColor Cyan
Write-Host "   • Environment variables (.env)" -ForegroundColor Gray
Write-Host "   • Instrument master CSV files" -ForegroundColor Gray
Write-Host "   • DhanHQ credentials" -ForegroundColor Gray
Write-Host "   • Feature flags" -ForegroundColor Gray
Write-Host ""

# Get production environment variables via Coolify API
Write-Host "[1/5] Fetching production environment variables..." -ForegroundColor Yellow

$pythonScript = @"
import requests
import json
import os

COOLIFY_API_URL = "http://72.62.228.112:8000/api/v1"
with open("COOLIFY API.txt", "r") as f:
    content = f.read()
    # Parse the API token from the file
    for line in content.split('\n'):
        if line.strip() and not line.strip().endswith(':'):
            COOLIFY_TOKEN = line.strip()
            break

APP_UUID = "x8gg0og8440wkgc8ow0ococs"

headers = {
    "Authorization": f"Bearer {COOLIFY_TOKEN}",
    "Content-Type": "application/json"
}

print("🔗 Fetching production environment variables...")
response = requests.get(
    f"{COOLIFY_API_URL}/applications/{APP_UUID}",
    headers=headers
)

if response.status_code != 200:
    print(f"❌ Failed to get app details: {response.text}")
    exit(1)

app_data = response.json()
env_vars = {}

# Extract environment variables
if "environment_variables" in app_data:
    env_vars = app_data["environment_variables"]
elif "data" in app_data and "environment_variables" in app_data["data"]:
    env_vars = app_data["data"]["environment_variables"]

# Save production env vars for reference
with open("production_db_export/production_env_vars.json", "w") as f:
    json.dump(env_vars, f, indent=2)

print("✅ Production environment variables saved")
print(f"   Found {len(env_vars)} variables")

# Generate local .env file
print("\n📝 Generating local .env file...")
local_env_vars = {
    # Database
    "DB_PASSWORD": "postgres123",
    
    # DhanHQ - NOT NEEDED for local (market streams disabled)
    # Leave empty since we're not connecting to DhanHQ in local environment
    "DHAN_CLIENT_ID": "",
    "DHAN_PIN": "",
    "DHAN_TOTP_SECRET": "",
    "DHAN_ACCESS_TOKEN": "",
    
    # Local configuration
    "VPS_IP": "localhost",
    "DOMAIN": "localhost",
    
    # Feature flags - DISABLED for local to prevent live trading
    "DISABLE_DHAN_WS": "true",
    "DISABLE_MARKET_STREAMS": "true",
    "STARTUP_START_STREAMS": "false",
    "STARTUP_LOAD_MASTER": "true",
    "STARTUP_LOAD_TIER_B": "false",
    
    # Optional settings
    "GREEKS_POLL_SECONDS": "15",
    "LOG_LEVEL": "DEBUG"  # More verbose logging for local dev
}

# Write .env file
env_content = "# ================================================================\n"
env_content += "# Trading Nexus - Local Development Environment\n"
env_content += "# Generated by local_setup_4_sync_config.ps1\n"
env_content += "# ================================================================\n\n"

env_content += "# --- Database (Local PostgreSQL) ---\n"
env_content += f"DB_PASSWORD={local_env_vars['DB_PASSWORD']}\n\n"

env_content += "# --- DhanHQ Credentials (NOT NEEDED - Market streams disabled) ---\n"
env_content += "# Empty because local environment doesn't connect to DhanHQ\n"
env_content += "# Market data streams are DISABLED for safe local testing\n"
env_content += f"DHAN_CLIENT_ID={local_env_vars['DHAN_CLIENT_ID']}\n"
env_content += f"DHAN_PIN={local_env_vars['DHAN_PIN']}\n"
env_content += f"DHAN_TOTP_SECRET={local_env_vars['DHAN_TOTP_SECRET']}\n"
env_content += f"DHAN_ACCESS_TOKEN={local_env_vars['DHAN_ACCESS_TOKEN']}\n\n"

env_content += "# --- Local Configuration ---\n"
env_content += f"VPS_IP={local_env_vars['VPS_IP']}\n"
env_content += f"DOMAIN={local_env_vars['DOMAIN']}\n\n"

env_content += "# --- Feature Flags (Local Development) ---\n"
env_content += "# Market connections DISABLED to prevent interference with production\n"
env_content += f"DISABLE_DHAN_WS={local_env_vars['DISABLE_DHAN_WS']}\n"
env_content += f"DISABLE_MARKET_STREAMS={local_env_vars['DISABLE_MARKET_STREAMS']}\n"
env_content += f"STARTUP_START_STREAMS={local_env_vars['STARTUP_START_STREAMS']}\n"
env_content += f"STARTUP_LOAD_MASTER={local_env_vars['STARTUP_LOAD_MASTER']}\n"
env_content += f"STARTUP_LOAD_TIER_B={local_env_vars['STARTUP_LOAD_TIER_B']}\n\n"

env_content += "# --- Optional Settings ---\n"
env_content += f"GREEKS_POLL_SECONDS={local_env_vars['GREEKS_POLL_SECONDS']}\n"
env_content += f"LOG_LEVEL={local_env_vars['LOG_LEVEL']}\n"

with open(".env", "w") as f:
    f.write(env_content)

print("✅ Local .env file created")
print("")
print("⚠️  IMPORTANT NOTES:")
print("   • Market data streams are DISABLED to prevent conflicts")
print("   • DhanHQ credentials are EMPTY (not needed for local testing)")
print("   • Database points to local PostgreSQL container")
print("   • LOG_LEVEL set to DEBUG for better troubleshooting")
print("   • This is a safe, isolated environment for development")
"@

$pythonScript | Out-File -FilePath ".\temp_sync_config.py" -Encoding UTF8
python .\temp_sync_config.py

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Configuration sync failed" -ForegroundColor Red
    exit 1
}

Remove-Item ".\temp_sync_config.py" -ErrorAction SilentlyContinue
Write-Host ""

# Check instrument master files
Write-Host "[2/5] Checking instrument master files..." -ForegroundColor Yellow
if (Test-Path ".\instrument_master\api-scrip-master-detailed.csv") {
    $csvSize = (Get-Item ".\instrument_master\api-scrip-master-detailed.csv").Length
    Write-Host "✅ Instrument master CSV found ($($csvSize / 1KB) KB)" -ForegroundColor Green
} else {
    Write-Host "⚠️  Instrument master CSV not found" -ForegroundColor Yellow
    Write-Host "   You may need to download it from production or DhanHQ" -ForegroundColor Yellow
}
Write-Host ""

# Check migrations
Write-Host "[3/5] Checking database migrations..." -ForegroundColor Yellow
$migrationCount = (Get-ChildItem -Path ".\migrations" -Filter "*.sql").Count
Write-Host "✅ Found $migrationCount migration files" -ForegroundColor Green
Write-Host ""

# Create local data directories if needed
Write-Host "[4/5] Setting up local data directories..." -ForegroundColor Yellow
$directories = @("logs", "tmp_live_chunks", "production_db_export")
foreach ($dir in $directories) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
        Write-Host "   Created: $dir/" -ForegroundColor Gray
    }
}
Write-Host "✅ Data directories ready" -ForegroundColor Green
Write-Host ""

# Display configuration summary
Write-Host "[5/5] Configuration Summary:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  📝 Environment File:        NOT CONFIGURED (not needed)roundColor Cyan
Write-Host "  🔐 DhanHQ Credentials:      Copied from production" -ForegroundColor Cyan
Write-Host "  🌊 Market Streams:          DISABLED (safe for local)" -ForegroundColor Cyan
Write-Host "  📊 Database:                Local PostgreSQL" -ForegroundColor Cyan
Write-Host "  📈 Instrument Master:       $(if (Test-Path '.\instrument_master\api-scrip-master-detailed.csv') { 'Present' } else { 'Missing' })" -ForegroundColor Cyan
Write-Host "  🔍 Log Level:               DEBUG" -ForegroundColor Cyan
Write-Host ""

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  Step 4 Complete!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next step: Run ./local_setup_5_start_and_verify.ps1" -ForegroundColor Yellow
Write-Host "           to start all services and verify the setup" -ForegroundColor Yellow
Write-Host ""
