services:
  learn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://tradingnexus.pro/api/v2
      NEXT_PUBLIC_PORTAL_API_TOKEN: portal-signups-token
      NODE_ENV: production
      PORT: 3000
    restart: always
